# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 04:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20170401_0724'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='category_id',
            new_name='category',
        ),
    ]
