# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-07 03:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20170404_0409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='route_name',
            field=models.CharField(db_index=True, max_length=20),
        ),
    ]
